spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate # JPA only checks if classes match schema; it will NOT alter tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true # Safe fallback to baseline if database already has tables

app:
  cookie:
    secure: false
    same-site: "Lax"
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}