spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:https://aniverse.com}